---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  Template for automating Task Definitions of an existing ECS cluster.

Parameters:
  ECSCluster:
    Type: String
    Description: AWS ECS Cluster Name
  ECRImage:
    Type: String
    Description: Name of Image to Deploy in Container
  ImageTag:
    Type: String
    Description: Version Tag for Image
  COINBASEAPIKEY:
    Type: String
    Description: API Key For Interfacing with CoinBase
  COINBASEAPISECRET:
    Type: String
    Description: API Secret Key For Interfacing with CoinBase
  REDISURL:
    Type: String
    Description: Redis Connection URL
  SLACKAPITOKEN:
    Type: String
    Description: Slack API Token
  STAGEPREFIX:
    Type: String
    Description: Prefix for Multi-Stage Deployments.

Resources:
  CloudwatchLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['-', [ECSLogGroup, !Ref 'AWS::StackName']]
      RetentionInDays: 14
  SlackTipBotDefinition:
    Type: "AWS::ECS::TaskDefinition"
    Properties: 
      Volumes:
        - Name: slack-tipbot-vol
      Family: !Join [ '-', [ slack-tipbot, !Ref STAGEPREFIX]]
      NetworkMode: bridge
      ContainerDefinitions:
        - Image: !Join [':', [!Ref ECRImage, !Ref ImageTag]] 
          Environment:
            - Name: COINBASE_API_KEY
              Value: !Ref COINBASEAPIKEY
            - Name: COINBASE_API_SECRET
              Value: !Ref COINBASEAPISECRET
            - Name: REDIS_URL
              Value: !Ref REDISURL
            - Name: SLACK_API_TOKEN
              Value: !Ref SLACKAPITOKEN
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref 'CloudwatchLogsGroup'
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: !Join [ '-', [ slack-tipbot, !Ref STAGEPREFIX]]
          Memory: 256
          Name: !Join [ '-', [ slack-tipbot, !Ref STAGEPREFIX]]
          PortMappings:
            - ContainerPort: 9292
              Protocol: tcp
  SlackTipBotService:
    Type: "AWS::ECS::Service"
    Properties: 
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      ServiceName: !Join [ '-', [ slack-tipbot-service, !Ref STAGEPREFIX]] 
      TaskDefinition: !Ref SlackTipBotDefinition

Outputs:
  TaskDef:
    Value: !Ref SlackTipBotDefinition
  ServiceDef:
    Value: !Ref SlackTipBotService